dependencies:
  - matplotlib #==3.1.2
  - numpy #==1.17.4
  - pandas #==0.25.3
  #- scipy #==1.3.3
  - tqdm #==4.57.0
  #- shapely
  - Cartopy #==0.18.0
  - xarray #==0.16.2
  - dask #==2.8.1
  #- intake
  - intake-esm
  - fsspec
  - gcsfs
  - seaborn
